# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbuild, mbot2, random
import time

@event.start
def on_start():
    cyberpi.audio.set_vol(10)
    cyberpi.console.set_font(12)
    cyberpi.console.println("Press “B” to start obstacle avoidance")
    cyberpi.console.println("Press “A” to restart")
    while not cyberpi.controller.is_press('b'):
      time.sleep(0.1)

    while True:
      cyberpi.led.show('red orange yellow green cyan')
      if mbuild.ultrasonic2.get(1) > 20:
        mbot2.forward(40)
        time.sleep(0.1)

      else:
        cyberpi.audio.play_until('jump')
        mbot2.straight(-15)
        # A randomness is designed to reduce the chance of the car getting stuck at a certain Angle.
        #
        # Not doing random can also achieve a good obstacle avoidance effect.
        if random.randint(1, 2) == 1:
          cyberpi.led.show('orange yellow cyan black black')
          mbot2.turn_left(50)
          cyberpi.audio.play('wow')
          time.sleep(1)

        else:
          cyberpi.led.show('black black cyan yellow orange')
          mbot2.turn_right(50)
          cyberpi.audio.play('laugh')
          time.sleep(1)

@event.is_press('a')
def is_btn_press():
    cyberpi.restart()

