# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi

@event.is_press('b')
def is_btn_press_b():
    cyberpi.console.println("кнопка B нажата")

@event.is_press('a')
def is_btn_press_a():
    cyberpi.console.clear()

@event.smaller_than(90, "light_sensor")
def on_compare_than():
    cyberpi.led.off("all")

@event.is_press('down')
def is_joy_press():
    cyberpi.console.println("джойстик вниз нажат")

@event.is_shake
def on_is_shake():
    cyberpi.console.print("hello world")

@event.start
def on_start():
    cyberpi.console.clear()
    cyberpi.audio.set_vol(15)
    cyberpi.audio.play('running-water')
    cyberpi.console.print("makeblock")
    cyberpi.led.show('red orange yellow green cyan')
    cyberpi.audio.play_until('magic')

