# generated by mBlock5 for CyberPi
# codes make you happy

import event, cyberpi, time, mbot2

@cyberpi.event.upload_broadcast("music")
def on_upload_mode_message():
    cyberpi.audio.set_vol(100)
    cyberpi.audio.set_tempo(100)
    if cyberpi.upload_broadcast.get("music") == 'duo':
      cyberpi.audio.play_music(60, 0.25)
      cyberpi.led.play('meteor_green')
      mbot2.turn(-90)

    if cyberpi.upload_broadcast.get("music") == 'so':
      cyberpi.audio.play_music(67, 0.25)
      cyberpi.led.play('flash_orange')
      mbot2.forward(50, 1)

    if cyberpi.upload_broadcast.get("music") == 'la':
      cyberpi.audio.play_music(69, 0.25)
      mbot2.turn(90)
      cyberpi.led.play('firefly')

